version: "3"

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-setup:/opt/oracle/scripts/setup
      - oracle-startup:/opt/oracle/scripts/startup
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-L",
          "system/oracle@//localhost:1521/XEPDB1",
          "AS",
          "SYSDBA",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
  oracle-setup:
  oracle-startup:
